title: "Spirit Connect Fantasy"
title_zh: "灵接幻想"
description: "Copy and update human consciousness and memory to the digital world"
description_zh: "将人类意识与记忆复制并更新至数字世界"
url: https://fulongli.github.io
baseurl: "/Spirit-Connect-Fantasy"
timezone: Europe/London
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
